services:
  - type: web
    name: Eclipse-MD
    runtime: docker
    repo: https://github.com/horlapookie/Eclipse-MD
    branch: main
    plan: free
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production

      - key: BOT_PREFIX
        value: .

      - key: BOT_NUMBER
        sync: false

      - key: BOT_SESSION_DATA
        sync: false
